# Generated by Django 2.1.3 on 2019-02-16 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0002_auto_20190216_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedframe',
            name='camera_name',
            field=models.TextField(blank=True, default='Camera 1'),
        ),
        migrations.AlterField(
            model_name='capturedframe',
            name='students',
            field=models.ManyToManyField(to='attendance.Student'),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='end',
            field=models.DateField(default=datetime.datetime(2019, 2, 16, 23, 44, 31, 953250)),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='start',
            field=models.DateField(default=datetime.datetime(2019, 2, 16, 23, 44, 31, 953250)),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Identification Number'),
        ),
    ]
