# Generated by Django 2.1.1 on 2018-09-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=100)),
                ('captured_frames', models.ManyToManyField(blank=True, to='attendance.CapturedFrame')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identification Number')),
                ('full_name', models.CharField(max_length=100)),
                ('face_id', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='working_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendances',
                                    to='attendance.WorkingDay'),
        ),
        migrations.AddField(
            model_name='capturedframe',
            name='students',
            field=models.ManyToManyField(blank=True, to='attendance.Student', verbose_name='Students in Image'),
        ),
    ]
