# Generated by Django 2.1.1 on 2018-09-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('face_id', models.CharField(blank=True, max_length=250)),
                ('captured_frames', models.ManyToManyField(to='attendance.CapturedFrame')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identification Number')),
                ('full_name', models.CharField(max_length=100)),
                ('face_id', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('lectures_attendances', models.ManyToManyField(blank=True, to='attendance.LectureAttendance')),
            ],
        ),
        migrations.AddField(
            model_name='capturedframe',
            name='students',
            field=models.ManyToManyField(to='attendance.Student', verbose_name='Students in Image'),
        ),
    ]
