# Generated by Django 2.1.1 on 2018-09-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturedframe',
            name='students',
        ),
        migrations.RemoveField(
            model_name='lectureattendance',
            name='captured_frames',
        ),
        migrations.AddField(
            model_name='capturedframe',
            name='lecture_attendance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='captured_frames', to='attendance.LectureAttendance'),
        ),
    ]
