# Generated by Django 2.1.1 on 2018-09-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0002_auto_20180915_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedframe',
            name='lecture_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_frames',
                                    to='attendance.LectureAttendance'),
        ),
    ]
