# Generated by Django 2.1.1 on 2018-09-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0002_auto_20180914_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
