# Generated by Django 2.1.1 on 2018-09-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0003_auto_20180915_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.TextField()),
                ('captured_frame',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_ids',
                                   to='attendance.CapturedFrame')),
            ],
        ),
    ]
