# Generated by Django 2.1.1 on 2018-09-14 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0004_auto_20180914_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectureattendance',
            old_name='full_name',
            new_name='lecture_name',
        ),
        migrations.RemoveField(
            model_name='lectureattendance',
            name='face_id',
        ),
    ]
