# Generated by Django 2.1.1 on 2018-09-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0005_auto_20180914_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureattendance',
            name='captured_frames',
            field=models.ManyToManyField(null=True, to='attendance.CapturedFrame'),
        ),
    ]
