# Generated by Django 2.1.1 on 2018-09-16 02:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0005_student_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='url',
        ),
    ]
