# Generated by Django 2.1.3 on 2018-11-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0006_remove_student_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedframe',
            name='students',
            field=models.ManyToManyField(to='attendance.Student'),
        ),
    ]
