# Generated by Django 2.1.1 on 2018-09-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0006_auto_20180914_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedframe',
            name='students',
            field=models.ManyToManyField(null=True, to='attendance.Student', verbose_name='Students in Image'),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='captured_frames',
            field=models.ManyToManyField(blank=True, to='attendance.CapturedFrame'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='lectures_attendances',
            field=models.ManyToManyField(null=True, to='attendance.LectureAttendance'),
        ),
    ]
