# Generated by Django 2.1.3 on 2018-12-12 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0007_capturedframe_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureattendance',
            name='end',
            field=models.DateField(default=datetime.datetime(2018, 12, 13, 0, 15, 17, 714597)),
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='start',
            field=models.DateField(default=datetime.datetime(2018, 12, 13, 0, 15, 17, 714597)),
        ),
    ]
