# Generated by Django 2.1.1 on 2018-09-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0007_auto_20180914_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedframe',
            name='students',
            field=models.ManyToManyField(blank=True, to='attendance.Student', verbose_name='Students in Image'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='lectures_attendances',
            field=models.ManyToManyField(blank=True, to='attendance.LectureAttendance'),
        ),
    ]
