# Generated by Django 2.1.3 on 2019-02-09 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0008_auto_20181213_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureattendance',
            name='end',
            field=models.DateField(default=datetime.datetime(2019, 2, 9, 14, 31, 10, 26569)),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='start',
            field=models.DateField(default=datetime.datetime(2019, 2, 9, 14, 31, 10, 25569)),
        ),
    ]
