# Generated by Django 2.1.1 on 2018-09-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0008_auto_20180914_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
