# Generated by Django 2.1.1 on 2018-09-14 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0009_auto_20180914_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingday',
            old_name='lectures_attendances',
            new_name='lecture_attendances',
        ),
    ]
