# Generated by Django 2.1.1 on 2018-09-15 05:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0011_auto_20180915_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingday',
            old_name='lecture_attendance',
            new_name='lecture_attendances',
        ),
    ]
