# Generated by Django 2.1.1 on 2018-09-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0012_auto_20180915_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='lecture_attendances',
            field=models.ManyToManyField(blank=True, related_name='lecture_attendance_list',
                                         to='attendance.LectureAttendance'),
        ),
    ]
