# Generated by Django 2.1.1 on 2018-09-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.ManyToManyField(to='rest_api.Student', verbose_name='Students in Image')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('face_id', models.CharField(blank=True, max_length=250)),
                ('captured_frames', models.ManyToManyField(to='rest_api.CapturedFrame')),
            ],
        ),
        migrations.AddField(
            model_name='date',
            name='lectures_attendances',
            field=models.ManyToManyField(to='rest_api.LectureAttendance'),
        ),
    ]
